In [1]:
import numpy as np

In [2]:
a_one  = np.array([7,2,7,5])
a_one

array([7, 2, 7, 5])

In [4]:
a_two = np.array([[2,3,4,5],[3,7,8,9]])
a_two.shape

(2, 4)

In [6]:
a_three = np.zeros([4,3,2])
a_three

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [9]:
a_three[0,0,0]=1
a_three[1,0]=2
a_three[2]=3
a_three

array([[[1., 0.],
        [0., 0.],
        [0., 0.]],

       [[2., 2.],
        [0., 0.],
        [0., 0.]],

       [[3., 3.],
        [3., 3.],
        [3., 3.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [17]:
# operations
# scalars
a_one
a_one +2
a_one*2
a_one/2
a_one**2
a_one

array([7, 2, 7, 5])

In [21]:
b_one = np.array([17,12,19,20])
b_one - a_one
a_one * b_one
a_one + b_one

array([24, 14, 26, 25])

In [29]:
a_two.shape
b_two = np.full((4,2),10)
b_two
# a_two * b_two

array([[10, 10],
       [10, 10],
       [10, 10],
       [10, 10]])

In [30]:
# Actual multiplication
np.dot(a_two,b_two)

array([[140, 140],
       [270, 270]])

In [3]:
import numpy as np
a = np.array([0,2,3,4])
b = np.array([1,1,3,1])

In [4]:
a == b

array([False, False,  True, False])

In [36]:
np.logical_and(a,b)

array([False,  True,  True,  True])

In [37]:
np.sin(a)

array([ 0.        ,  0.90929743,  0.14112001, -0.7568025 ])

In [38]:
np.mean(a_one)

np.float64(5.25)

In [39]:
# Reduction
a_two


array([[2, 3, 4, 5],
       [3, 7, 8, 9]])

In [40]:
np.sum(a_two)

np.int64(41)

In [42]:
np.sum(a_two,axis =1)

array([14, 27])

In [44]:
np.min(a_two,axis=0)

array([2, 3, 4, 5])

In [47]:
a_three
np.sum(a_three,axis=1)

array([[1., 0.],
       [2., 2.],
       [9., 9.],
       [0., 0.]])