In [3]:
import numpy as np

In [4]:
arr = np.array([1,2,3,4])
arr[-1]

np.int64(4)

In [4]:
arr = np.array([[1,2,3,4,5],[1,5,6,7,8]])
print(arr[1,1])

5


In [5]:
arr[:3,:3]

array([[1, 2, 3],
       [1, 5, 6]])

In [8]:
# 3d array
arr = np.random.randint(-3,7,(2,3,4))
arr

array([[[ 0, -1,  5, -1],
        [-3, -3,  6, -1],
        [-2,  2, -2,  3]],

       [[ 6,  5,  1,  5],
        [ 5,  0, -3,  4],
        [ 5,  6,  6,  1]]], dtype=int32)

In [12]:
arr[0,1]

array([-3, -3,  6, -1], dtype=int32)

In [13]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [14]:
arr[0:4]

array([1, 2, 3, 4])

In [18]:
arr_2 = np.array([[1,2,3,4,5],[6,7,8,9,8],[10,11,12,13,14]])
arr_2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9,  8],
       [10, 11, 12, 13, 14]])

In [23]:
arr_2[:2,2:3]

array([[3],
       [8]])

In [ ]:
arr_2[2,::2] #start : end : step

In [24]:
# indexing using array
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [27]:
arr[np.array([1,7,8,9])]

array([ 2,  8,  9, 10])

In [28]:
# masking 
b= arr<5
arr[b]

array([1, 2, 3, 4])