In [2]:
import numpy as np

In [2]:
arr  = np.array([[1,2,3,4,5],[6,7,8,9,10]])
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [3]:
arr.shape

(2, 5)

In [4]:
arr.reshape(1,10)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]])

In [5]:
arr.reshape(2,5,1)

array([[[ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5]],

       [[ 6],
        [ 7],
        [ 8],
        [ 9],
        [10]]])

In [2]:
# repeat an array
import numpy as np
arr = np.array([1,2,3,4]
               )

In [3]:
np.repeat(arr,3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4])

In [4]:
arr = np.array([[1,2],[3,4]])
arr
np.repeat(arr,3,axis=0)

array([[1, 2],
       [1, 2],
       [1, 2],
       [3, 4],
       [3, 4],
       [3, 4]])

In [17]:
# vertical stack

v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])
np.vstack([v1,v2,v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [19]:
v3 = np.array([[1,1,1,1],[2,2,2,2]])
v3

array([[1, 1, 1, 1],
       [2, 2, 2, 2]])

In [22]:
np.vstack([v3,v3])

array([[1, 1, 1, 1],
       [2, 2, 2, 2],
       [1, 1, 1, 1],
       [2, 2, 2, 2]])

In [5]:
h1 = np.array([[1,1],[2,2]])
h1
h2 = np.array([[3,3,3],[4,5,3]])
h2

array([[3, 3, 3],
       [4, 5, 3]])

In [6]:
np.hstack([h1,h2])

array([[1, 1, 3, 3, 3],
       [2, 2, 4, 5, 3]])

# expanding and squeezing

In [10]:
arr = np.zeros((4,1,3))
arr.shape

(4, 1, 3)

In [12]:

arr1 = np.squeeze(arr)
arr1.shape

(4, 3)

In [16]:
# Expanding

arr = np.zeros((4,3,2))
np.expand_dims(arr,axis =(0,2)).shape

(1, 4, 1, 3, 2)